version: '3.8'

services:
  motorvisuales:
    build: .
    container_name: motorvisuales
    restart: unless-stopped
    volumes:
      - .:/app
      - ./cookies.txt:/app/cookies.txt:rw
    networks:
      - traefik

networks:
  traefik:
    external: true
    name: traefik_traefik
